### ISSUE TITLE
Could this be used to deliver the latest episode via an URL based request?

### ISSUE THREAD

**Issue by netclift** [scour/feedjira-podcast#1]
I just posted this to Stack Exchange:
http://softwarerecs.stackexchange.com/questions/18913/what-code-can-be-adapted-to-parse-a-podcast-rss-or-itunes-xml-feed-and-deliver-t

Is this something I might do with your code?

(As a non-coder, I need to find someone to help me make this work. ;-))

Steve

**Comment by farski** [comment]
@netclift If this is still something you're looking to do, this gem would get you most of the way there. You'd have to build a small web service around it to handle the request and spit out the data you want, but that would be fairly simple. Another option that would be easy would be to use AWS Lambda with API Gateway. You wouldn't even need to run a server.
